spring:
  config:
    import:
      - classpath:/application-local.yml
      - classpath:/application-dev.yml
      - classpath:/application-prod.yml
      - classpath:/application-cicd.yml
      - classpath:/secret.yml