# dev 서버 설정 yml
spring:
  config:
    activate:
      on-profile: cicd

  jpa:
    hibernate:
      ddl-auto: create

# Todo: 추후 logback 설정으로 넘길 것 (임시)
logging:
  charset:
    console: utf-8

  level:
    root: info
    org.springframework.web: info
    com.backend.ttukttak_v2.advice: info
    org.hibernate: info

