# dev 서버 설정 yml
spring:
  config:
    activate:
      on-profile: local

  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ttukttak
    username: root
    password: root

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: solution
      username: root
      password: 1234

    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: mysql
      encoding: UTF-8

# Todo: 추후 logback 설정으로 넘길 것 (임시)
logging:
  charset:
    console: utf-8

  level:
    root: debug
    org.springframework.web: debug
    com.backend.ttukttak_v2.advice: debug
    org.hibernate: debug