# dev 서버 설정 yml
spring:
  config:
    activate:
      on-profile: dev

# Todo: 추후 logback 설정으로 넘길 것 (임시)
logging:
  charset:
    console: utf-8

  level:
    root: error
    org.springframework.web: error
    com.backend.ttukttak_v2.advice: error
    org.hibernate: error