# 공통 설정 yml
server:
  port: 5201

spring:
  config:
    activate:
      on-profile: local

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  health:
    db:
      enabled: true
    redis:
      enabled: true
    defaults:
      enabled: true

slack:
  webhook:
    notification:
      error: https://hooks.slack.com/services/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

