# 공통 설정 yml
server:
  port: 5201

spring:
  config:
    activate:
      on-profile: common
    import:
      - classpath:/resource-common/application-common-secret.yml
  endpoint:
    health:
      show-details: always
      enabled: true
  health:
    db:
      enabled: true
    redis:
      enabled: true
    defaults:
      enabled: true

oauth:
  token-url: "http://localhost:5201/api/auth/oauth/token"