# 공통 설정 yml
server:
  port: 5201

spring:
  config:
    activate:
      on-profile: common

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  health:
    db:
      enabled: true
    redis:
      enabled: true
    defaults:
      enabled: true

