# dev 서버 Database 설정 yml
spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: none

  datasource:
    hikari:
      maximum-pool-size: 4

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password:

  sql:
    init:
      platform: postgres