# dev 서버 설정 yml
spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:/resource-local/application-dev-datasource.yml

# 추후 logback 설정으로 넘길 것 (임시)
logging:
  charset:
    console: utf-8
  level:
    root: info
    org.springframework.web: debug
    org.hibernate: error