# 로컬 환경 설정 yml (로컬에서만 사용 푸시금지)
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:/resource-local/application-local-datasource.yml
logging:
  charset:
    console: utf-8
  level:
    root: info
    org.springframework.web: debug
    org.hibernate: error
