# 로컬 Database yml (로컬에서만 사용 푸시금지)
spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create-drop
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: q3143118
  sql:
    init:
      platform: postgres